# Generated by Django 4.2.7 on 2023-12-12 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='bed_rooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='district_location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bathrooms',
            new_name='restrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='num_rooms',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.ImageField(default=-1, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rent_cost',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rent_type',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
