# Generated by Django 4.2.7 on 2023-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_bedrooms_property_bed_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('num_rooms', models.IntegerField()),
                ('bath_rooms', models.IntegerField()),
                ('bed_rooms', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('district_location', models.CharField(max_length=255)),
                ('rent_cost', models.FloatField()),
                ('rent_type', models.IntegerField()),
                ('description', models.TextField()),
                ('photos', models.BinaryField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
