# Generated by Django 4.2.7 on 2023-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_realestate_title_alter_realestate_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='photos',
        ),
        migrations.AddField(
            model_name='realestate',
            name='photos',
            field=models.ManyToManyField(to='app.photo'),
        ),
    ]
