# Generated by Django 4.2.7 on 2023-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photo_remove_realestate_photos_realestate_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='app.photo'),
        ),
    ]
