# Generated by Django 4.2.7 on 2023-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_realestate_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
