# Generated by Django 4.2.7 on 2023-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_realestate_options_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
