# Generated by Django 4.2.7 on 2023-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_realestate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='owner_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='telegram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='whatsapp',
            field=models.BooleanField(null=True),
        ),
    ]
