# Generated by Django 4.2.7 on 2023-12-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_realestate_owner_number_realestate_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
