# Generated by Django 4.2.7 on 2023-12-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_realestate_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.realestate'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leased_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='photos',
            field=models.ManyToManyField(blank=True, to='app.photo'),
        ),
    ]
