# Generated by Django 4.2.7 on 2023-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_realestate_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='real_estate', to='app.photo'),
        ),
    ]
