# Generated by Django 4.2.7 on 2023-12-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_realestate_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(max_length=255),
        ),
    ]
