# Generated by Django 4.2.7 on 2023-12-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_realestate_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasecontract',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_contracts', to='app.realestate'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='bath_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='bed_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='num_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
