# Generated by Django 4.2.7 on 2023-12-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.realestate'),
        ),
    ]
